FROM mcr.microsoft.com/dotnet/sdk:8.0.100
WORKDIR /src
# Copy project files to image to ensure SDK resolution during build
COPY . .
WORKDIR /src/src/Api
EXPOSE 80
CMD ["dotnet", "watch", "run", "--urls", "http://+:80"]
