// <auto-generated />
using System;
using JobTicketSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BillingAddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingAddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasFilter("[AccountNumber] IS NOT NULL");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BillRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("LaborRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Employees");
                });

                    b.Property<string>("WorkSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EndedAtUtc");

                    b.HasIndex("JobTicketId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("EmployeeId", "EndedAtUtc");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.TimeEntryAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdjustedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdjustmentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Hours")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("NewBillableHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("NewEndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NewHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewLaborHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NewNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("NewStartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OriginalBillableHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("OriginalEndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OriginalHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OriginalLaborHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OriginalNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("OriginalStartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TimeEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TimeEntryId");

                    b.ToTable("TimeEntryAdjustments");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.Customer", "Customer")
                        .WithMany("Equipment")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobTicketSystem.Domain.Entities.Customer", "OwnerCustomer")
                        .WithMany()
                        .HasForeignKey("OwnerCustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JobTicketSystem.Domain.Entities.Customer", "ResponsibleBillingCustomer")
                        .WithMany()
                        .HasForeignKey("ResponsibleBillingCustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JobTicketSystem.Domain.Entities.ServiceLocation", "ServiceLocation")
                        .WithMany("Equipment")
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("OwnerCustomer");

                    b.Navigation("ResponsibleBillingCustomer");

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.InvoiceSummary", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.Customer", "Customer")
                        .WithMany("InvoiceSummaries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobTicketSystem.Domain.Entities.JobTicket", "JobTicket")
                        .WithOne("InvoiceSummary")
                        .HasForeignKey("JobTicketSystem.Domain.Entities.InvoiceSummary", "JobTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("JobTicket");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.JobTicket", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.Employee", "AssignedManagerEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedManagerEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobTicketSystem.Domain.Entities.Customer", "BillingPartyCustomer")
                        .WithMany()
                        .HasForeignKey("BillingPartyCustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JobTicketSystem.Domain.Entities.Customer", "Customer")
                        .WithMany("JobTickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobTicketSystem.Domain.Entities.Equipment", "Equipment")
                        .WithMany("JobTickets")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobTicketSystem.Domain.Entities.ServiceLocation", "ServiceLocation")
                        .WithMany("JobTickets")
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedManagerEmployee");

                    b.Navigation("BillingPartyCustomer");

                    b.Navigation("Customer");

                    b.Navigation("Equipment");

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.JobTicketEmployee", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.Employee", "Employee")
                        .WithMany("JobTickets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobTicketSystem.Domain.Entities.JobTicket", "JobTicket")
                        .WithMany("AssignedEmployees")
                        .HasForeignKey("JobTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("JobTicket");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.JobTicketFile", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobTicketSystem.Domain.Entities.JobTicket", "JobTicket")
                        .WithMany("Files")
                        .HasForeignKey("JobTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobTicketSystem.Domain.Entities.Employee", "UploadedByEmployee")
                        .WithMany()
                        .HasForeignKey("UploadedByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobTicketSystem.Domain.Entities.JobWorkEntry", "WorkEntry")
                        .WithMany()
                        .HasForeignKey("WorkEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipment");

                    b.Navigation("JobTicket");

                    b.Navigation("UploadedByEmployee");

                    b.Navigation("WorkEntry");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.JobTicketPart", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.Employee", "AddedByEmployee")
                        .WithMany()
                        .HasForeignKey("AddedByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobTicketSystem.Domain.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobTicketSystem.Domain.Entities.JobTicket", "JobTicket")
                        .WithMany("Parts")
                        .HasForeignKey("JobTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobTicketSystem.Domain.Entities.Part", "Part")
                        .WithMany("JobTicketParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobTicketSystem.Domain.Entities.JobTicketPart", "ReplacedByJobTicketPart")
                        .WithMany("ReplacedJobTicketParts")
                        .HasForeignKey("ReplacedByJobTicketPartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AddedByEmployee");

                    b.Navigation("Equipment");

                    b.Navigation("JobTicket");

                    b.Navigation("Part");

                    b.Navigation("ReplacedByJobTicketPart");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.JobWorkEntry", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.Employee", "Employee")
                        .WithMany("WorkEntries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobTicketSystem.Domain.Entities.JobTicket", "JobTicket")
                        .WithMany("WorkEntries")
                        .HasForeignKey("JobTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("JobTicket");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.Part", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.PartCategory", "PartCategory")
                        .WithMany("Parts")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobTicketSystem.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Parts")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PartCategory");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.Vendor", "Vendor")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.Part", "Part")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobTicketSystem.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.ServiceLocation", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.Customer", "Customer")
                        .WithMany("ServiceLocations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.TimeEntry", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.Employee", "Employee")
                        .WithMany("TimeEntries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobTicketSystem.Domain.Entities.JobTicket", "JobTicket")
                        .WithMany("TimeEntries")
                        .HasForeignKey("JobTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("JobTicket");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.TimeEntryAdjustment", b =>
                {
                    b.HasOne("JobTicketSystem.Domain.Entities.TimeEntry", "TimeEntry")
                        .WithMany("Adjustments")
                        .HasForeignKey("TimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeEntry");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("InvoiceSummaries");

                    b.Navigation("JobTickets");

                    b.Navigation("ServiceLocations");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.Employee", b =>
                {
                    b.Navigation("JobTickets");

                    b.Navigation("TimeEntries");

                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("JobTickets");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.JobTicket", b =>
                {
                    b.Navigation("AssignedEmployees");

                    b.Navigation("Files");

                    b.Navigation("InvoiceSummary");

                    b.Navigation("Parts");

                    b.Navigation("TimeEntries");

                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.JobTicketPart", b =>
                {
                    b.Navigation("ReplacedJobTicketParts");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.Part", b =>
                {
                    b.Navigation("JobTicketParts");

                    b.Navigation("PurchaseOrderLines");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.PartCategory", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.ServiceLocation", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("JobTickets");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.TimeEntry", b =>
                {
                    b.Navigation("Adjustments");
                });

            modelBuilder.Entity("JobTicketSystem.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
