export { CustomersPage, EquipmentPage, PartsPage, ServiceLocationsPage } from './masterData/MasterDataPages'
export { PartsApprovalPage } from './approvals/ApprovalPages'
export { TimeApprovalPage } from './approvals/TimeApprovalPage'
export { ReportsPage } from './reports/ReportsPage'
export { UnauthorizedPage } from './users/UnauthorizedPage'
export { UsersPage } from './users/UsersPage'
export { SystemWikiPage } from './wiki/SystemWikiPage'
export { CompanyConfigurationPage } from './companyConfiguration/CompanyConfigurationPage'
export { TicketStatusFiltersPage } from './ticketStatusFilters/TicketStatusFiltersPage'

export { InventoryPage } from './InventoryPage'
export { PartRequestsPage } from './PartRequestsPage'
export { PartsUsageHistoryPage } from './PartsUsageHistoryPage'
export { EquipmentHistoryPage } from './EquipmentHistoryPage'
export { PurchasingWorkbenchPage } from './PurchasingWorkbenchPage'
export { SchedulePage } from './SchedulePage'
